### PR TITLE
add attributes to iFrame to allow fullscreen playback

### PR DESCRIPTION
**Pull request by lpirl**
This PR adds attributes to the iFrame, so fullscreen plackback will be allowed by browser.

Cheers for considering. :)

### CODE REVIEW

**Comment by lpirl** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

Very relevant; still ready to merge; happy to receive comments for enhancement; @kura seems to be AFK.

For the time being: there is [lpirl/pelican_vimeo](https://github.com/lpirl/pelican_vimeo) where all open PRs should be merged.

**Comment by kura** [comment]
Sorry, I didn't get a notification of this PR @lpirl.

**Comment by lpirl** [comment]
Yay, sweet, cheers for merging.

**Comment by kura** [comment]
No problem, thanks for the contribution. Feel free to yell at me if you have any PRs in the future. I dunno why I wasn't getting notified of the PRs.

**Comment by kura** [comment]
Np. Thanks for the contribution!

**Pull request merged**
